### ISSUE TITLE
Error requesting: https://bff.emea-prod.mobilesdk.mercedes-benz.com/v2/vehicles - 404 - 0 -

### ISSUE THREAD

**Issue by CDM040971** [ReneNulschDE/mbapi2020#307]
### The problem

I'm one of the "others" that has had to remove and reinstall Integration. 
Run the Windows Token Generator app which worked and provided both tokens - added the old pin figured it was wrong and so did a reset on the pin - Used the new pin. 
Post configuration the message says successful yet MercedesME 2020 Reports "Failed to Setup - Check Logs" 

** Deleted HACS Merc and redid the setup twice ~ yet same result each time **

**Log 1**

Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 10:41:52 PM (1 occurrences)
Last logged: 10:41:52 PM

Error setting up entry XXXXXX@outlook.com (Region: Europe) for mbapi2020
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mbapi2020/__init__.py", line 75, in async_setup_entry
    for car in masterdata.get("assignedVehicles"):
               ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'  

**Log 2**
This error originated from a custom integration.

Logger: custom_components.mbapi2020.webapi
Source: custom_components/mbapi2020/webapi.py:119
integration: MercedesME 2020 (documentation, issues)
First occurred: 10:41:52 PM (1 occurrences)
Last logged: 10:41:52 PM

Error requesting: https://bff.emea-prod.mobilesdk.mercedes-benz.com/v2/vehicles - 404 - 0 -

Hopefully I'm doing something silly 

### What version of MBAPI2020 do use?

New Beta v0.23.0,

### What was the last working version of MBAPI2020?

v0.21.0,

### What type of installation are you running?

Home Assistant Core

### Diagnostics information

[md1738667359180.json](https://github.com/user-attachments/files/18656977/md1738667359180.json)

[md1738667365082.json](https://github.com/user-attachments/files/18656986/md1738667365082.json)

**Comment by ReneNulschDE** [comment]
mmmhhh - the vehicle master data API is not available for your account. This is not a general problem. This is working on my side.

Could you log into the mercedes-benz website and check if you have cars in your account? (use the same account like the one that you used for the token creation)

**Comment by ReneNulschDE** [comment]
Could you try to generate the tokens with your wife's account? Delete the integration, restart HA and read the integration.

I have tested it with multiple accounts and I can't reproduce this. Did you made any other changes in your environment in the last days?

**Comment by Adri9102** [comment]
```
2025-02-04 19:44:44.020 DEBUG (MainThread) [custom_components.mbapi2020] Start async_setup_entry.
2025-02-04 19:44:44.021 DEBUG (MainThread) [custom_components.mbapi2020.client] WSL not detected - running in rlock mode
2025-02-04 19:44:44.021 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2025-02-04 19:44:44.021 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2025-02-04 19:44:44.245 ERROR (MainThread) [custom_components.mbapi2020.webapi] Error requesting: https://bff.emea-prod.mobilesdk.mercedes-benz.com/v2/vehicles - 418 - 0 - 
2025-02-04 19:44:44.245 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry mbapi2020 for mbapi2020
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 584, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mbapi2020/__init__.py", line 75, in async_setup_entry
    for car in masterdata.get("assignedVehicles"):
               ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

I have got the same issue after update of library

**Comment by ReneNulschDE** [comment]
This is a different error. Http418 was solved with v0.22.

**Comment by Adri9102** [comment]
> This is a different error. Http418 was solved with v0.22.

Yea, there was activity in HASC and I thought that it was the latest version. Works fine with v0.23

**Comment by johanvdk1** [comment]
Tokens stopped working. Now login with email apparently.

**Comment by ReneNulschDE** [comment]
@CDM040971 : Yust saw that your mobile number is from Australia. Did you selected APAC as the region? If yes and it is not working - let us discuss this in a private way. send me an email to mbdev.i307@nulsch.de

**Comment by ReneNulschDE** [comment]
Hi @HABrain,

Keep the version latest version 0.23

Best way is to 
- remove the integration. 
- Restart HA. 
- Readd the integration.
- use the [client tools](https://github.com/ReneNulschDE/mbapi2020/wiki/How%E2%80%90to:-create-the-access-and-refresh-token) to create the new tokens
- add the token in the HA component dialog


I assume that this topic is not related to this issue here...

**Comment by johanvdk1** [comment]
Can't use the old method anymore where a code is sent by mail. MB does not sent the mail anynore.

Instructions (Installation) under Home Assistant still state:
Use your MB-login email address. Your will receive a 6-digit code via email (valid for 15min).

However GITHUB gives the correct procedure: https://github.com/ReneNulschDE/mbapi2020/wiki/How%E2%80%90to:-create-the-access-and-refresh-token

The helper app generates the correct tokens.

All solved now, thanks.

From: Rene Nulsch ***@***.***>
Date: Wednesday, 5 February 2025 at 19:45
To: ReneNulschDE/mbapi2020 ***@***.***>
Cc: johanvdk1 ***@***.***>, Mention ***@***.***>
Subject: Re: [ReneNulschDE/mbapi2020] Error requesting: https://bff.emea-prod.mobilesdk.mercedes-benz.com/v2/vehicles - 404 - 0 - (Issue #307)


Hi @HABrain<https://github.com/HABrain>,

Keep the version latest version 0.23

Best way is to

  *   remove the integration.
  *   Restart HA.
  *   Readd the integration.
  *   use the client tools<https://github.com/ReneNulschDE/mbapi2020/wiki/How%E2%80%90to:-create-the-access-and-refresh-token> to create the new tokens
  *   add the token in the HA component dialog

I assume that this topic is not related to this issue here...

**Comment by HABrain** [comment]
> Hi @HABrain,
> 
> Keep the version latest version 0.23
> 
> Best way is to 
> - remove the integration. 
> - Restart HA. 
> - Readd the integration.
> - use the [client tools](https://github.com/ReneNulschDE/mbapi2020/wiki/How%E2%80%90to:-create-the-access-and-refresh-token) to create the new tokens
> - add the token in the HA component dialog
> 
> 
> I assume that this topic is not related to this issue here...
> 
> The next version of the component will have a reconfigure dialog... but I'm still working on it...

Thank you - it works 👍

**Comment by ReneNulschDE** [comment]
@johanvdk1 : you are right, I have to fix the docs - but the new way with the client tools is working. As described in the release notes. Keep in mind that…. No let me stop …. My mistake

**Comment by ReneNulschDE** [comment]
Disucussed offline - a password reset was needed.
