### ISSUE TITLE
Detected integration that accesses the `is_metric` property of the unit system

### ISSUE THREAD

**Issue by THW22** [ReneNulschDE/mbapi2020#74]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 11:42:44 (1 occurrences)
Last logged: 11:42:44

Detected integration that accesses the `is_metric` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for mbapi2020 using this method at custom_components/mbapi2020/__init__.py, line 529: not self._hass.config.units.is_metric:

**Comment by ReneNulschDE** [comment]
Hi, thx for reporting. This is solved in the Master Branch already since several days. Just need some time to produce a new release.

**Comment by ReneNulschDE** [comment]
Release published https://github.com/ReneNulschDE/mbapi2020/releases/tag/v0.6.8

**Comment by reinvk** [comment]
Hi, i got the following error now with home-assistant 2022.10.5

Logger: homeassistant.setup
Source: setup.py:192
First occurred: 22:55:00 (1 occurrences)
Last logged: 22:55:00

Setup failed for custom integration mbapi2020: 

Unable to import component: cannot import name 'US_CUSTOMARY_SYSTEM' from 'homeassistant.util.unit_system' 

(/usr/src/homeassistant/homeassistant/util/unit_system.py)

**Comment by ReneNulschDE** [comment]
The version 0.6.8 requires HA version 2022.11.
